// <auto-generated />
using ITS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITS.Migrations
{
    [DbContext(typeof(ITSContext))]
    [Migration("20181106195806_[Migration1]")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITS.Models.Datos_personales", b =>
                {
                    b.Property<long>("Id_datos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("A_materno")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("A_paterno")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Edad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id_datos");

                    b.ToTable("Datos_personales");
                });

            modelBuilder.Entity("ITS.Models.Tipo_usuario", b =>
                {
                    b.Property<long>("id_tipo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre_tipo_usuario")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id_tipo");

                    b.ToTable("Tipo_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
